/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCategoryForm: typeof import('./src/components/dialogs/AddCategoryForm.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseSelect: typeof import('./src/components/BaseSelect.vue')['default']
    BaseTextarea: typeof import('./src/components/BaseTextarea.vue')['default']
    Categories: typeof import('./src/components/home/Categories.vue')['default']
    ConfirmationDialogContent: typeof import('./src/components/dialogs/ConfirmationDialogContent.vue')['default']
    DeleteButton: typeof import('./src/components/DeleteButton.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Globe: typeof import('./src/components/Globe.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    ImageUploader: typeof import('./src/components/newProduct/ImageUploader.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Product: typeof import('./src/components/Product.vue')['default']
    ProductsCarousel: typeof import('./src/components/home/ProductsCarousel.vue')['default']
    ProductsGrid: typeof import('./src/components/home/ProductsGrid.vue')['default']
    RadiusMap: typeof import('./src/components/searchResults/RadiusMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/home/Search.vue')['default']
    SearchResultsContent: typeof import('./src/components/searchResults/SearchResultsContent.vue')['default']
    ToggleButton: typeof import('./src/components/ToggleButton.vue')['default']
  }
}
