/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Categories: typeof import('./src/components/home/Categories.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Product: typeof import('./src/components/home/Product.vue')['default']
    ProductsCarousel: typeof import('./src/components/home/ProductsCarousel.vue')['default']
    ProductsGrid: typeof import('./src/components/home/ProductsGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/home/Search.vue')['default']
  }
}
