services:
  mysql:
    env_file:
      - ".env"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    container_name: mysql
    image: mysql:8.4
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-boot:
    env_file:
      - ".env"
    environment:
      - DB_HOST=mysql
    image: spring-boot-backend
    container_name: spring-boot
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_volume:

networks:
  app_network:
    driver: bridge
