name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven" # Cache Maven dependencies

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/backend
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7) # Use short SHA as tag
          echo "Building and pushing image: $IMAGE_NAME:$IMAGE_TAG"
          cd backend && ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName="$IMAGE_NAME:$IMAGE_TAG" -DskipTests
          # Also tag and push as latest for Railway auto-deployments from main
          docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:latest"
        env:
          # Pass credentials for spring-boot:build-image Paketo builder
          DOCKER_CONFIG: ${{ runner.temp }}/.docker

      - name: Run tests and generate coverage report
        run: cd backend && ./mvnw verify

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: backend/target/site/jacoco/jacoco.xml
